runtime: python312

env_variables:
  FLASK_ENV: 'production'
  CLIENT_ID: 'client_id'
  CLIENT_SECRET: 'client_secret'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
